/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filtering;

import StringManipulation.FilterHTML;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author but-anonju_sd2022
 */
public class RemoveHTML extends javax.swing.JFrame {

    /**
     * Creates new form RemoveHTML
     */
    public RemoveHTML() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFilteredHTML = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOriginalHTML = new javax.swing.JTextArea();
        jButtonRemoveHTML = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaWordsCounted = new javax.swing.JTextArea();
        jButtonCountWords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaFilteredHTML.setColumns(20);
        jTextAreaFilteredHTML.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFilteredHTML);

        jTextAreaOriginalHTML.setColumns(20);
        jTextAreaOriginalHTML.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOriginalHTML);

        jButtonRemoveHTML.setText("Remove HTML Tags");
        jButtonRemoveHTML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveHTMLMouseClicked(evt);
            }
        });
        jButtonRemoveHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveHTMLActionPerformed(evt);
            }
        });

        jTextAreaWordsCounted.setColumns(20);
        jTextAreaWordsCounted.setRows(5);
        jScrollPane3.setViewportView(jTextAreaWordsCounted);

        jButtonCountWords.setText("Count words");
        jButtonCountWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountWordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jButtonRemoveHTML))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jButtonCountWords)))
                        .addGap(0, 210, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButtonRemoveHTML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonCountWords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveHTMLActionPerformed
/************************************************REMOVES THE HTML TAGS************************************************/
    private void jButtonRemoveHTMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveHTMLMouseClicked
        // TODO add your handling code here:
        String str = jTextAreaOriginalHTML.getText();
        FilterHTML filter = new FilterHTML();
        str = filter.removeHTML(str);
        jTextAreaFilteredHTML.setText(str);
    }//GEN-LAST:event_jButtonRemoveHTMLMouseClicked
/************************************************COUNTS THE WORD IN THE FILTERED TEXT AREA************************************************/
    private void jButtonCountWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountWordsActionPerformed
        // TODO add your handling code here:
        String sentence = jTextAreaFilteredHTML.getText();
//        sentence = sentence.replaceAll("\\<.*?\\>", "");
        String[] words = sentence.split("\\W");
        List<String> uniqueWords = new ArrayList();
        List<String> finalOutput = new ArrayList();
        String output = "";
        for (String word : words) {
            if (!uniqueWords.contains(word) && !word.isEmpty()) {
                uniqueWords.add(word);
            }
        }
        for (String text : uniqueWords) {
            int counter = 0;
            for (String original : words) {
                if (original.equals(text)) {
                    counter++;
                }
            }
            finalOutput.add(text + " = " + counter);
        }
        for (String res : finalOutput) {
            output += res + "\n";
        }
        jTextAreaWordsCounted.setText(output);
    }//GEN-LAST:event_jButtonCountWordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveHTML.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveHTML.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveHTML.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveHTML.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveHTML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCountWords;
    private javax.swing.JButton jButtonRemoveHTML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaFilteredHTML;
    private javax.swing.JTextArea jTextAreaOriginalHTML;
    private javax.swing.JTextArea jTextAreaWordsCounted;
    // End of variables declaration//GEN-END:variables
}
