/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigdata;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
//import javax.swing.JLabel;

/**
 *
 * @author 2ndyrGroupB
 */
public class Activity_3 extends javax.swing.JFrame {

    /**
     * Creates new form Activity_3
     */
    public Activity_3() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stopWatchPanel = new javax.swing.JPanel();
        startBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        minutes = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        centiseconds = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hours = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentTimePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        currentTime = new javax.swing.JLabel();
        countUpPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        countUp = new javax.swing.JLabel();
        countUpStartBtn = new javax.swing.JButton();
        countDownPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        countDown = new javax.swing.JLabel();
        countDownStartBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        stopWatchPanel.setBackground(new java.awt.Color(204, 204, 255));

        startBtn.setText("Start");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        stopBtn.setText("Stop");
        stopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopBtnMouseClicked(evt);
            }
        });

        minutes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minutes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutes.setText("00");

        seconds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seconds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seconds.setText("00");

        centiseconds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centiseconds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centiseconds.setText("00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Stop Watch");

        hours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hours.setText("00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(":");

        javax.swing.GroupLayout stopWatchPanelLayout = new javax.swing.GroupLayout(stopWatchPanel);
        stopWatchPanel.setLayout(stopWatchPanelLayout);
        stopWatchPanelLayout.setHorizontalGroup(
            stopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopWatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(stopWatchPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(stopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopWatchPanelLayout.createSequentialGroup()
                        .addComponent(hours)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(centiseconds, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stopWatchPanelLayout.createSequentialGroup()
                        .addComponent(startBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopBtn)))
                .addGap(43, 43, 43))
        );
        stopWatchPanelLayout.setVerticalGroup(
            stopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopWatchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(stopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centiseconds, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(stopWatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn)
                    .addComponent(stopBtn))
                .addGap(19, 19, 19))
        );

        currentTimePanel.setBackground(new java.awt.Color(204, 153, 255));

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Current Time");

        currentTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout currentTimePanelLayout = new javax.swing.GroupLayout(currentTimePanel);
        currentTimePanel.setLayout(currentTimePanelLayout);
        currentTimePanelLayout.setHorizontalGroup(
            currentTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentTimePanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(currentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(currentTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        currentTimePanelLayout.setVerticalGroup(
            currentTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(currentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        countUpPanel.setBackground(new java.awt.Color(204, 153, 255));

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Count Up");

        countUp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        countUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countUp.setText("0");

        countUpStartBtn.setText("Start");
        countUpStartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countUpStartBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout countUpPanelLayout = new javax.swing.GroupLayout(countUpPanel);
        countUpPanel.setLayout(countUpPanelLayout);
        countUpPanelLayout.setHorizontalGroup(
            countUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countUpPanelLayout.createSequentialGroup()
                .addGroup(countUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(countUpPanelLayout.createSequentialGroup()
                        .addGroup(countUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(countUpPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(countUp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(countUpPanelLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(countUpStartBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(countUpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        countUpPanelLayout.setVerticalGroup(
            countUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(countUpStartBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        countDownPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Count Down");

        countDown.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        countDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countDown.setText("100");

        countDownStartBtn.setText("Start");
        countDownStartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countDownStartBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout countDownPanelLayout = new javax.swing.GroupLayout(countDownPanel);
        countDownPanel.setLayout(countDownPanelLayout);
        countDownPanelLayout.setHorizontalGroup(
            countDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countDownPanelLayout.createSequentialGroup()
                .addGroup(countDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(countDownPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(countDown, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(countDownPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(countDownPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(countDownStartBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        countDownPanelLayout.setVerticalGroup(
            countDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countDownPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countDown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(countDownStartBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(countUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopWatchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countDownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(currentTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopWatchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countDownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean stop = false;

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
        stop = false;
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int o = 0;; o++) { // this is an infinite loop
                    for (int h = 0;; h++) {//
                        for (int i = 0; i < 60; i++) { // this for minutes
                            for (int j = 0; j < 60; j++) { // j is for the seconds
                                for (int k = 0; k < 100; k++) { // k is the centiseconds
                                    if (stop) {
                                        break;
                                    }
                                    NumberFormat nf = new DecimalFormat("00");
                                    hours.setText(nf.format(h));
                                    minutes.setText(nf.format(i));
                                    seconds.setText(nf.format(j));
                                    centiseconds.setText(nf.format(k));
                                    try {
                                        Thread.sleep(10);
                                    } catch (Exception e) {
                                    }

                                }
                                if (stop) { // if stop button is clicked then the milliseconds will stop
                                    break;
                                }
                            }
                            if (stop) { // if stop button is clicked then the seconds will stop
                                break;
                            }
                        }
                        if (stop) { // if stop button is clicked then the minutes will stop
                            break;
                        }
                    }
                    
                }
            }
        }
        ).start();    
    }//GEN-LAST:event_startBtnMouseClicked

    private void stopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseClicked
        // TODO add your handling code here:
        stop = true; // when stop button is clicked, then the variable stop will be true
    }//GEN-LAST:event_stopBtnMouseClicked

    private void countUpStartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countUpStartBtnMouseClicked
        // TODO add your handling code here:
        String count = countUp.getText();

        new Thread(new Runnable() {
            int time = Integer.parseInt(count);

            public void run() {
                while (time <= 100) {
                    countUp.setText(String.valueOf(time));
                    time++;
                    try {
                        Thread.sleep(1000L);
                    } catch (InterruptedException ie) {
                        System.out.println(ie.getMessage());
                    }
                }
                while (time >= 100) {
                    countUpPanel.setBackground(Color.RED);
                    countUpPanel.setBackground(Color.PINK);
                }
            }
        }).start();
    }//GEN-LAST:event_countUpStartBtnMouseClicked

    private void countDownStartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countDownStartBtnMouseClicked
        // TODO add your handling code here:
        String count = countDown.getText();

        new Thread(new Runnable() {
            int time = Integer.parseInt(count);

            public void run() {
                while (time >= 0) {
                    countDown.setText(String.valueOf(time));
                    time--;
                    try {
                        Thread.sleep(1000L);
                    } catch (InterruptedException ie) {
                        System.out.println(ie.getMessage());
                    }
                }
                while (time <= 0) {
                    countDownPanel.setBackground(Color.CYAN);
//                    countDownPanel.setBackground(Color.blue);
                }
            }
        }).start();
    }//GEN-LAST:event_countDownStartBtnMouseClicked

    public void currentTime() {
        new Thread(new Runnable() {
            public void run() {
                try {
                    while (true) {
                        Date d = new java.util.Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("hh:MM:ss a");
                        currentTime.setText(sdf.format(d));
                        Thread.sleep(1000);
                        Activity_3.class.cast(currentTime);
                    }

                } catch (Exception e) {
                }
            }
        }).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Activity_3 activity = new Activity_3();
                activity.setVisible(true);
                activity.currentTime();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel centiseconds;
    private javax.swing.JLabel countDown;
    private javax.swing.JPanel countDownPanel;
    private javax.swing.JButton countDownStartBtn;
    private javax.swing.JLabel countUp;
    private javax.swing.JPanel countUpPanel;
    private javax.swing.JButton countUpStartBtn;
    private javax.swing.JLabel currentTime;
    private javax.swing.JPanel currentTimePanel;
    private javax.swing.JLabel hours;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minutes;
    private javax.swing.JLabel seconds;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JPanel stopWatchPanel;
    // End of variables declaration//GEN-END:variables
}
